# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Evenki spellchecker"
evn = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Evenki, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
evn = "TRANSLATE: A spellchecker for Evenki, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.evn"

[windows]
system_product_code = "{1BA9D318-E293-4935-B69A-E6D7B8136CF1}_is1"
legacy_product_codes = [
    { value = "CDD14853-8AD0-4A3C-BC4D-FE3E991DD145", kind = "nsis" },
    { value = "6C9404F7-0611-4523-B563-F8AA7AFDD865", kind = "nsis" }
]

[package.speller]
name = "Evenki"
version = "0.1.1"

[package.grammar]
name = "Evenki"
version = "0.1.0"

[package.tts-text-proc]
name = "Evenki"
version = "0.1.0"

[package.hyphenator]
name = "__UNDEFINED__"
version = "0.1.0"
