template = "https://github.com/giellalt/template-lang-und"
rev_id = 208
template_sha = "8692838fc7cf77fe5ec2a217ecdaea7f79547a51"

[replacements]
__REPO__ = "lang-evn"
__UND2C__ = "evn"
__UNDEFINED__ = "Evenki"
__UND__ = "evn"
