template = "https://github.com/giellalt/template-lang-und"
rev_id = 281
template_sha = "818353eecbfc8e1309992f6739dfde72a0afbec0"

[replacements]
__GLOTTOLOG_ID__ = "even1259"
__REPO__ = "lang-evn"
__UND2C__ = "evn"
__UNDEFINED__ = "Evenki"
__UND__ = "evn"
