template = "https://github.com/giellalt/template-lang-und"
rev_id = 278
template_sha = "58c9d1b66bc21da4ce588378206dd02d219954ae"

[replacements]
__GLOTTOLOG_ID__ = "even1259"
__REPO__ = "lang-evn"
__UND2C__ = "evn"
__UNDEFINED__ = "Evenki"
__UND__ = "evn"
