template = "https://github.com/giellalt/template-lang-und"
rev_id = 256
template_sha = "4e2ddf168a2aaf68d2c29db9e79e44e1dc4c2b76"

[replacements]
__GLOTTOLOG_ID__ = "even1259"
__REPO__ = "lang-evn"
__UND2C__ = "evn"
__UNDEFINED__ = "Evenki"
__UND__ = "evn"
